apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app.fullname" . }}-stable
  namespace: {{ include "sample-app.namespace" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sample-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
{{- if eq .Values.workload.kind "Rollout" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app.fullname" . }}-canary
  namespace: {{ include "sample-app.namespace" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sample-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
